### ISSUE TITLE
NameError: uninitialized constant I18n::HashRefinements 

### ISSUE THREAD

**Issue by kwisatz** [mainio/decidim-module-term_customizer#78]
See https://github.com/ruby-i18n/i18n/pull/602

```
decidim@marklar:~/decidim$ bundle exec rails db:migrate --trace                                   [58/1934]
** Invoke db:migrate (first_time)                                                                                  
** Invoke db:load_config (first_time)                                                                              ** Invoke environment (first_time)
** Execute environment                                                                                             rails aborted!      
NameError: uninitialized constant I18n::HashRefinements                                                            /home/decidim/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/bundler/gems/decidim-module-term_customizer-0e823f4f768f/li
b/decidim/term_customizer/i18n_backend.rb:9:in `<class:I18nBackend>'                                           
/home/decidim/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/bundler/gems/decidim-module-term_customizer-0e823f4f768f/li
b/decidim/term_customizer/i18n_backend.rb:8:in `<module:TermCustomizer>'                                           /home/decidim/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/bundler/gems/decidim-module-term_customizer-0e823f4f768f/li
b/decidim/term_customizer/i18n_backend.rb:7:in `<module:Decidim>'                                                  /home/decidim/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/bundler/gems/decidim-module-term_customizer-0e823f4f768f/li
b/decidim/term_customizer/i18n_backend.rb:6:in `<main>'                                                            
/home/decidim/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bootsnap-1.10.2/lib/bootsnap/load_path_cache/core_ext/
kernel_require.rb:30:in `require'                                                                                  
/home/decidim/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bootsnap-1.10.2/lib/bootsnap/load_path_cache/core_ext/
kernel_require.rb:30:in `require'
/home/decidim/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/bundler/gems/decidim-module-term_customizer-0e823f4f768f/li
b/decidim/term_customizer/engine.rb:9:in `block in <class:Engine>'
/home/decidim/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/railties-5.2.6/lib/rails/initializable.rb:32:in `insta
nce_exec'
/home/decidim/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/railties-5.2.6/lib/rails/initializable.rb:32:in `run'
/home/decidim/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/railties-5.2.6/lib/rails/initializable.rb:61:in `block
 in run_initializers'
/home/decidim/.rbenv/versions/2.7.5/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
/home/decidim/.rbenv/versions/2.7.5/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_com
ponent'
/home/decidim/.rbenv/versions/2.7.5/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
/home/decidim/.rbenv/versions/2.7.5/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
/home/decidim/.rbenv/versions/2.7.5/lib/ruby/2.7.0/tsort.rb:347:in `each'
/home/decidim/.rbenv/versions/2.7.5/lib/ruby/2.7.0/tsort.rb:347:in `call'
/home/decidim/.rbenv/versions/2.7.5/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
/home/decidim/.rbenv/versions/2.7.5/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
/home/decidim/.rbenv/versions/2.7.5/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
/home/decidim/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/railties-5.2.6/lib/rails/initializable.rb:60:in `run_i
nitializers'
/home/decidim/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/railties-5.2.6/lib/rails/application.rb:361:in `initia
lize!'
/home/decidim/decidim-4motion/config/environment.rb:5:in `<main>'
/home/decidim/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bootsnap-1.10.2/lib/bootsnap/load_path_cache/core_ext/
kernel_require.rb:30:in `require'
/home/decidim/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bootsnap-1.10.2/lib/bootsnap/load_path_cache/core_ext/
kernel_require.rb:30:in `require'
/home/decidim/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/railties-5.2.6/lib/rails/application.rb:337:i[13/1934]
e_environment!'
/home/decidim/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/railties-5.2.6/lib/rails/application.rb:520:in `block 
in run_tasks_blocks'
/home/decidim/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
/home/decidim/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
/home/decidim/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
/home/decidim/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_w
ith_call_chain'
/home/decidim/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/home/decidim/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_
chain'
/home/decidim/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:243:in `block in invoke_p
rerequisites'
/home/decidim/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `each'
/home/decidim/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `invoke_prerequisi
tes'
/home/decidim/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:218:in `block in invoke_w
ith_call_chain'
/home/decidim/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/home/decidim/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_
chain'
/home/decidim/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:243:in `block in invoke_p
rerequisites'
/home/decidim/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `each'
/home/decidim/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `invoke_prerequisi
tes'
/home/decidim/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:218:in `block in invoke_w
ith_call_chain'
/home/decidim/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/home/decidim/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_
chain'
/home/decidim/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
/home/decidim/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_tas
k'
/home/decidim/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 l
evels) in top_level'
/home/decidim/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
/home/decidim/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in t
op_level'
/home/decidim/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_t
hreads'
/home/decidim/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
/home/decidim/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/railties-5.2.6/lib/rails/commands/rake/rake_command.rb
:23:in `block in perform'
/home/decidim/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_e
xception_handling'
/home/decidim/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/railties-5.2.6/lib/rails/commands/rake/rake_command.rb
:20:in `perform'
/home/decidim/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/railties-5.2.6/lib/rails/command.rb:48:in `invoke'
/home/decidim/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/railties-5.2.6/lib/rails/commands.rb:18:in `<main>'
/home/decidim/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bootsnap-1.10.2/lib/bootsnap/load_path_cache/core_ext/
kernel_require.rb:30:in `require'
/home/decidim/.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/bootsnap-1.10.2/lib/bootsnap/load_path_cache/core_ext/
kernel_require.rb:30:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:migrate => db:load_config => environment
```

**Comment by lahdeero** [comment]
Fixed by e027889704ef97456c667c4f4f5b8bd96d162e8b
